### ISSUE TITLE
gerrymander loops endlessly

### ISSUE THREAD

**Issue by larsks** [berrange/gerrymander#28]
When attempting to use gerrymander (`gerrymander --status open --owner self`), it enters an infinite loop.  The logic in `gerrymander.operations.OperationQuery ` is suspect; it looks like it will keep calling `self.client.run`, which will call `mycb`, which will set `c.gotany=True`, which will cause the loop to continue...

**Comment by berrange** [comment]
This is caused by new Gerrit version which broke its API, dropping its previous syntax for iterating over results. It is fixed in GIT in a combination of

https://github.com/berrange/gerrymander/commit/38488bc976b8c93ffba5fa6b0b27f6b09c90dea3
https://github.com/berrange/gerrymander/commit/472beed7a2701200dfdd531ef4a96cc84241a95b

**Comment by berrange** [comment]
Marking as closed since its fix in git master
